config/routes.rb
AventonesLanding::Application.routes.draw do
  resources :surveys
  get '/stats' => 'stats#index', as: 'stats'
  root :to => 'surveys#index'
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :email, :would_charge, :would_pay, :ipaddress, :useragent
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  layout 'stats'

  USERS = { "veamos" => "lasestadisticas" }

  before_filter :authenticate

  def index
    @surveys = Survey.order('id DESC')
  end


  private

  def authenticate
    authenticate_or_request_with_http_digest do |username|
      USERS[username]
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys, only: [:id] }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey, only: [:id] }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new
    @survey = Survey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(params[:survey])
    @survey.useragent = request.user_agent.to_s
    @survey.ipaddress = request.remote_ip.to_s

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update
    @survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <title>Aventones - Sé de los primeros en unirte</title>
  <meta name="description" content="Con Aventones podrás encontrar gente con quién compartir el auto para ahorrar gasolina, tiempo y dinero, además de contribuir al medio ambiente. Sé de los primeros en unirte." />
  <meta name="keywords" content="Aventones, Aventón, car pooling, car pool, green transport" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements and pseudo classes -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <script type="text/javascript" src="/javascripts/selectivizr-min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="iconochiquito.png" />
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-32588047-1']);
    _gaq.push(['_trackPageview']);
    // _gaq.push(['_trackEvent', 'Pre-registro', 'Submit', 'Me apunto']);

    (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</head>
<body>

<div class="container">
  
  <div class="aventones-box">
    <div class="aventones-logo"><div class="logo-bx"><%= link_to("Aventones", root_url, :class => "logo") %></div></div>

    <div id="app">
        <!--[if lt IE 7]><p class=chromeframe>Tu navegador es <em>antiguo!</em> <a href="http://browsehappy.com/">Actualiza tu navegador</a> o <a href="http://www.google.com/chromeframe/?redirect=true">instala Google Chrome Frame</a> para usar este sitio mejor.</p><![endif]-->
        
    </div>

    <footer>
      <p id="corporate">¿Trabajas en responsabilidad social, sustentabilidad o
      recursos humanos de una empresa?, Aventones Corporativo es un proyecto
      que quieres tener en tu empresa, ¡te lo aseguramos! <%= link_to "Conoce más sobre Aventones corporativo >>", "http://aventones.com/conocer-mas/" %></p>
    </footer>

    <div id="aventones_tooltip" class="modal hide fade">
      <div class="modal-header">
        <a href="" class="close" data-dismiss="modal">&times;</a>
        <h3>¿Qué es Aventones?</h3>
      </div>
      <div class="modal-body">
        <p><strong>Aventones</strong> es un portal en Internet que te ayudará a
        encontrar ya sea amigos o amigos de tus amigos con quién compartir
        coche.</p>

        <p>En aventones podrás publicar tu ruta de forma muy sencilla, y el
        sistema buscará entre todas las rutas publicadas para encontrar
        coincidencias con la tuya, y así mostrarte gente con la cuál podrías
        compartir el coche.</p>

        <p>Es una solución social y sustentable de movilidad.</p>
      </div>

    </div>
    
    <div id="image_attribution" class="modal hide fade">
      <div class="modal-header">
        <a href="" class="close" data-dismiss="modal">&times;</a>
        <h3>Derechos de las imágenes.</h3>
      </div>
      <div class="modal-body">
        <h2>Dando crédito a quien lo merece por las imágenes de fondo.</h2>
        <p>Fotografías por:</p>
        <ol>
        <li><%= link_to "Vivek Chugh", "http://www.sxc.hu/profile/vivekchugh", :target => "_blank" %>: 
        <%= link_to "A drive on Camps Bay", "http://www.sxc.hu/photo/1204516", :target => "_blank" %></li>
        <li><%= link_to "Ariel da Silva Parreira", "http://www.sxc.hu/profile/arinas74", :target => "_blank" %>: 
        <%= link_to "Car speed", "http://www.sxc.hu/photo/1360987", :target => "_blank" %> y 
        <%= link_to "Road Blur", "http://www.sxc.hu/photo/1158482", :target => "_blank" %></li>
        <li><%= link_to "Thomas van den Berg", "http://www.sxc.hu/profile/thomasje", :target => "_blank" %>: 
        <%= link_to "Mountain Road", "http://www.sxc.hu/photo/1351192", :target => "_blank" %></li>
        <li><%= link_to "Lena Povrzenic", "http://www.sxc.hu/profile/zitherica", :target => "_blank" %>: 
        <%= link_to "Road", "http://www.sxc.hu/photo/1104290", :target => "_blank" %></li>
        <li><%= link_to "Juan Alberto Ramírez Díaz", "http://www.sxc.hu/profile/jard_jard", :target => "_blank" %>: 
        <%= link_to "Páramo", "http://www.sxc.hu/photo/1102202", :target => "_blank" %></li>
        <li><%= link_to "Jeff Hire", "http://www.sxc.hu/profile/gun4hire", :target => "_blank" %>: 
        <%= link_to "Speeding 2", "http://www.sxc.hu/photo/1091826", :target => "_blank" %></li>
        </ol>
      </div>

    </div>
    
  </div><!-- End of .aventones-box -->
  <div class="aventones-footer">© 2012 Redes de Aventones SA de CV. Todos los derechos reservados. <a href="#image_attribution" data-toggle="modal">Derechos de las imágenes.</a></div>
</div><!-- End of .container -->

  <script type="text/javascript" charset="utf-8">
    jQuery(function() {
      new App({ el: $("#app") });
    });
  </script>
  
</body>
</html>

app/views/layouts/stats.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Aventones - Sé de los primeros en unirte</title>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="iconochiquito.png" />
  <style type="text/css">
    body {
      background-color: #fff;
      color: #333;
      font-family: verdana, arial, helvetica, sans-serif;
      font-size: 13px;
      line-height: 18px; }

    p, ol, ul, td {
      font-family: verdana, arial, helvetica, sans-serif;
      font-size: 13px;
      line-height: 18px; }

    pre {
      background-color: #eee;
      padding: 10px;
      font-size: 11px; }

    a {
      color: #000;
      &:visited {
        color: #666; }
      &:hover {
        color: #fff;
        background-color: #000; } }

    table { border-collapse: collapse; }
    td, th { border: 1px #ccc solid; padding: 3px 6px; }
    tbody tr:nth-child(odd) td { background: #eee; }

    div {
      &.field, &.actions {
        margin-bottom: 10px; } }

    .container {
      padding-bottom: 100px;
    }

    #notice {
      color: green; }

    .field_with_errors {
      padding: 2px;
      background-color: red;
      display: table; }

    #error_explanation {
      width: 450px;
      border: 2px solid red;
      padding: 7px;
      padding-bottom: 0;
      margin-bottom: 20px;
      background-color: #f0f0f0;
      h2 {
        text-align: left;
        font-weight: bold;
        padding: 5px 5px 5px 15px;
        font-size: 12px;
        margin: -7px;
        margin-bottom: 0px;
        background-color: #c00;
        color: #fff; }
      ul li {
        font-size: 12px;
        list-style: square; } }
    </style>
  </head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/stats/index.html.erb
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Would charge</th>
      <th>Would pay</th>
      <th>Timestamp</th>
      <th>IP address</th>
      <th>User Agent</th>
    </tr>
  </thead>

  <tbody>
  <% @surveys.each do |survey| %>
    <tr>
      <td><%= survey.email %></td>
      <td><%= survey.would_charge %></td>
      <td><%= survey.would_pay %></td>
      <td><%= survey.created_at %></td>
      <td><%= survey.ipaddress %></td>
      <td><%= survey.useragent %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :would_charge %><br />
    <%= f.text_field :would_charge %>
  </div>
  <div class="field">
    <%= f.label :would_pay %><br />
    <%= f.text_field :would_pay %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>